# ROS node settings
traj_server_rate: 20 # Should be < 40 Hz for serial comms
data_channel: "dynamixel"
use_traj_server: True

# Serial device info
devices:
  - devname: /dev/ttyUSB0
    baudrate: 9600 #115200
    num_channels: 1
    cmd_spec: '2.2'
    cmd_format: '%0.2f'
