# ROS node settings
traj_server_rate: 20 # Should be 20 Hz or less for serial comms
data_channel: "pressure_control"
use_traj_server: True

# HID Device Info
# The first controller
devices:
  - vendor_id: 5824
    product_id: 1158
    serial_number: 6467390
    num_channels: 8
    cmd_spec: '2.1'
    cmd_format: '%0.2f'

  # The second controller (connected via serial)
  - devname: /dev/ttyUSB0
    baudrate: 9600 #115200
    num_channels: 1
    cmd_spec: '2.2'
    cmd_format: '%0.2f'