# ROS node settings
traj_server_rate: 20 # Should be 20 Hz or less for serial comms
data_channel: "pressure_control"
use_traj_server: True

# Serial device info
devices:
  - devname: /dev/ttyACM0
    baudrate: 115200 #115200
    num_channels: 8
    cmd_spec: '2.1'
    cmd_format: '%0.2f'


