
# Top-level settings
settings:
    traj_type: 'interp'  # Types include: 'waveform', 'interp'


# Place all of the type-specific settings in here
config:
    interp_type: none   # can be: 'linear', 'cubic', 'none'
    setpoints:
        # [time, position [x,y,z], orientation [x,y,z]]
        main:
            - [0.00,   0]     
            - [1.00,   90] 
            - [2.00,   90]  
            - [4.00,   0]            
            


        prefix:
            - [0.00,  0]
            - [1.0,  0] 
              

        suffix:
            - [4.0,   0]